# # This workflow will install Python dependencies, run tests and lint. It will then deploy to our ImPaaS Cluster.
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: ImPaaS Manager

# on: push

# permissions:
#   contents: read
#   packages: write

# jobs:
#   deploy:

#     runs-on: ubuntu-latest

#     if: github.ref == 'refs/heads/main'

#     steps:
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3
      
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v3
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         push: true
#         tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest 

#     - name: ImPaaS-Deploy
#       id: impaas-deploy
#       uses: /impaas/impaas-deploy@v1.9
#       with:
#         app-name: ${{ secrets.APP_NAME }}
#         deployment-token: ${{ secrets.TEAM_DEPLOYMENT_TOKEN }}
